# general params
general:
    cores: 8
reads_prime:
  - R1
  - R2
tomerge:
  FALSE
resourcesfolder:
  ../resources/
resultsfolder:
  ../results/
fastqfiles:
  - mother_16s
mergedfile:
  holobrom_16s
  
# align filter
alifilt:
  minscore: 30.00
  
# trim and filter
filterandtrim:
  truncLen: 200
  maxN: 0
  maxEE: 2
  truncQ: 2
  matchIDs: TRUE
  verbose: TRUE
  multithread: 15

# dereplication
dereplication:
  simult_reads: 1e06

# obiclean
obiclean:
  ratio: 0.05

# Abundance filtering
abb_filt: 
  mincount: 10

# clustering
clustering:
  minsim: 0.97
  
# taxa
assign_taxon:
    fasta: ../../pipelino/TaxonomyDatabase/silva_nr_v138_train_set.fa
    sim_thld: 0.97